In [1]:
class manusia:
    def __init__(self, warnaRambut, berat, tinggi, nama = "bambang", umur = 60):
        # inisialisasi atribut
        self.nama = nama
        self.umur = umur
        self.warnaRambut = warnaRambut
        self.berat = berat
        self.tinggi = tinggi
    # method
    def berjalan(self):
        print(self.nama + " sedang berjalan")
    def berbicara(self):
        print(self.nama + " sedang berbicara")
    def berlari(self):
        print(self.nama + " sedang berlari")
    def gantiWarnaRambut(self, warna):
        print(self.nama + " ganti warna rambut dari " + self.warnaRambut + " menjadi " + warna)
        self.warnaRambut = warna
    def BMI(self):
        return self.berat / (self.tinggi ** 2)
# membuat objek manusia
andi = manusia(nama="Andi", umur = 20, warnaRambut="hitam", berat=70, tinggi=1.7)
andi.berjalan()

Andi sedang berjalan


In [2]:
andi.umur, andi.nama, andi.warnaRambut

(20, 'Andi', 'hitam')

In [3]:
andi.gantiWarnaRambut("toska")

Andi ganti warna rambut dari hitam menjadi toska


In [4]:
andi.BMI()

24.221453287197235

In [5]:
andi.berlari()

Andi sedang berlari


In [6]:
class coba:
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def tambah(self):
        return self.a + self.b
    def kurang(self):
        return self.a - self.b
    def kali(self):
        return self.a * self.b
    def bagi(self):
        return self.a / self.b

coba1 = coba(10, 5)
coba1.tambah()

15

# Inheritance

In [7]:
# Inheritance
class mahasiswa(manusia, coba):
    def __init__(self, nama, umur, warnaRambut, berat, tinggi, nim, jurusan, a, b):
        manusia.__init__(self, warnaRambut, berat, tinggi, nama, umur)
        coba.__init__(self, a, b)
        self.nim = nim
        self.jurusan = jurusan
    def belajar(self):
        print(self.nama + " sedang belajar")
    def makan(self):
        print(self.nama + " sedang makan")
    def tidur(self):
        print(self.nama + " sedang tidur")
    def gantiJurusan(self, jurusan):
        print(self.nama + " ganti jurusan dari " + self.jurusan + " menjadi " + jurusan + " dengan NIM " , self.a , self.b)
        self.jurusan = jurusan


# membuat objek mahasiswa
budi = mahasiswa(nama = "Budi", umur =  20, warnaRambut = "hitam", berat = 70, tinggi = 1.7, nim = "123456", jurusan = "Teknik Informatika", a = 10, b = 5)

In [8]:
budi.nama

'Budi'

In [9]:
budi.gantiJurusan("Teknik Industri")
budi.jurusan

Budi ganti jurusan dari Teknik Informatika menjadi Teknik Industri dengan NIM  10 5


'Teknik Industri'

# Pytorch NN Module

In [10]:
import torch 
import torch.nn as nn

In [11]:
class customNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(customNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, output_dim)
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out
    

model = customNN(10, 20, 2)
model.forward(torch.randn(1, 10))

c:\Users\Toko Ferdi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\linear.py:96: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)
  self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))


tensor([[-0.2864,  0.1301]], grad_fn=<AddmmBackward0>)

In [16]:
class customNeuranN(nn.Module):
  def __init__(self, input_dim, hidden_dim, output_dim):
    super(customNeuranN, self).__init__()
    self.fc = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),
        nn.ReLU(),
        nn.Linear(hidden_dim, output_dim),
        nn.Sigmoid()
    )
  def forward(self, x):
    out = self.fc(x)
    return out

model = customNeuranN(10, 20, 2)
model.forward(torch.randn(1, 10))

tensor([[0.3456, 0.5607]], grad_fn=<SigmoidBackward0>)

In [17]:
# bikin custom neural network multitask
class customNeuranNetwork(nn.Module):
  def __init__(self, input_dim, hidden_dim, output_dim):
    super(customNeuranN, self).__init__()
    self.fc = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),
        nn.ReLU(),
        nn.Linear(hidden_dim, output_dim),
        nn.Sigmoid()
    )
    self.reg = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),
        nn.ReLU(),
        nn.Linear(hidden_dim, output_dim),
    )

    self.clf = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),
        nn.ReLU(),
        nn.Linear(hidden_dim, output_dim),
        nn.Sigmoid()
    )

  def forward(self, x):
    x = self.fc(x)
    out_reg = self.reg(x)
    out_clf = self.clf(x)
    return out_reg, out_clf

model = customNeuranN(10, 20, 2)
model.forward(torch.randn(1, 10))

tensor([[0.4659, 0.3583]], grad_fn=<SigmoidBackward0>)